version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Run code coverage
          command: npm run coverage
      - store_artifacts:
          path: ~/app/dist/
          destination: app

  deploy:
    docker:
      - image: circleci/node:14
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run: |
          ssh ubuntu@3.17.187.27 "cd ~/home/fullstack-todo-nestjs && git fetch && git reset --hard origin/master && ./deploy.sh"
